language: java
jdk:
  - openjdk15
script:
  - ./mvnw clean install
#deploy:
#  provider: heroku
#  api_key:
#    secure: $HEROKU_API_KEY
#  app: experimental-ci-cd
#  on:
#    branch: main
before_install:
  - chmod +x mvnw